name: Build & Run Tests CashFlow API

trigger:
  branches:
    include:
      - dev
      - hml
      - master
  paths:
    include:
      - src/*
      - tests/*

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build

- task: DotNetCoreCLI@2
  displayName: Run Unit & Integration Tests
  inputs:
    command: test
